definitions:
  api.AddressBatchRequest:
    properties:
      address:
        type: string
      coin:
        type: integer
    type: object
  api.AddressesRequest:
    items:
      properties:
        address:
          type: string
        coin:
          type: integer
      type: object
    type: array
  api.ApiError:
    properties:
      status_code:
        type: integer
      status_message:
        type: string
    type: object
  api.CoinStatus:
    properties:
      error:
        type: string
      height:
        type: integer
    type: object
  api.ObserverResponse:
    properties:
      status:
        type: string
    type: object
  api.Webhook:
    properties:
      subscriptions:
        type: object
      webhook:
        type: string
      xpub_subscriptions:
        type: object
    type: object
  blockatlas.Collection:
    properties:
      address:
        type: string
      category_address:
        type: string
      coin:
        type: integer
      description:
        type: string
      external_link:
        type: string
      id:
        type: string
      image_url:
        type: string
      name:
        type: string
      nft_version:
        type: string
      slug:
        type: string
      symbol:
        type: string
      total:
        type: integer
      type:
        type: string
    type: object
  blockatlas.CollectionPage:
    items:
      properties:
        address:
          type: string
        category_address:
          type: string
        coin:
          type: integer
        description:
          type: string
        external_link:
          type: string
        id:
          type: string
        image_url:
          type: string
        name:
          type: string
        nft_version:
          type: string
        slug:
          type: string
        symbol:
          type: string
        total:
          type: integer
        type:
          type: string
      type: object
    type: array
  blockatlas.Delegation:
    properties:
      delegator:
        $ref: '#/definitions/blockatlas.StakeValidator'
        type: object
      metadata:
        type: object
      status:
        type: string
      value:
        type: string
    type: object
  blockatlas.DelegationsBatch:
    properties:
      address:
        type: string
      balance:
        type: string
      coin:
        $ref: '#/definitions/coin.ExternalCoin'
        type: object
      delegations:
        $ref: '#/definitions/blockatlas.DelegationsPage'
        type: object
      details:
        $ref: '#/definitions/blockatlas.StakingDetails'
        type: object
      error:
        type: string
    type: object
  blockatlas.DelegationsBatchPage:
    items:
      properties:
        address:
          type: string
        balance:
          type: string
        coin:
          $ref: '#/definitions/coin.ExternalCoin'
          type: object
        delegations:
          $ref: '#/definitions/blockatlas.DelegationsPage'
          type: object
        details:
          $ref: '#/definitions/blockatlas.StakingDetails'
          type: object
        error:
          type: string
      type: object
    type: array
  blockatlas.DelegationsPage:
    items:
      properties:
        delegator:
          $ref: '#/definitions/blockatlas.StakeValidator'
          type: object
        metadata:
          type: object
        status:
          type: string
        value:
          type: string
      type: object
    type: array
  blockatlas.DocsResponse:
    properties:
      docs:
        type: object
    type: object
  blockatlas.Resolved:
    properties:
      coin:
        type: integer
      result:
        type: string
    type: object
  blockatlas.StakeValidator:
    properties:
      details:
        $ref: '#/definitions/blockatlas.StakingDetails'
        type: object
      id:
        type: string
      info:
        $ref: '#/definitions/blockatlas.StakeValidatorInfo'
        type: object
      status:
        type: boolean
    type: object
  blockatlas.StakeValidatorInfo:
    properties:
      description:
        type: string
      image:
        type: string
      name:
        type: string
      website:
        type: string
    type: object
  blockatlas.StakingDetails:
    properties:
      locktime:
        type: integer
      minimum_amount:
        type: string
      reward:
        $ref: '#/definitions/blockatlas.StakingReward'
        type: object
      type:
        type: string
    type: object
  blockatlas.StakingReward:
    properties:
      annual:
        type: number
    type: object
  blockatlas.Tx:
    properties:
      block:
        description: Height of the block the transaction was included in
        type: integer
      coin:
        description: SLIP-44 coin index of the platform
        type: integer
      date:
        description: Unix timestamp of the block the transaction was included in
        type: integer
      direction:
        description: Transaction Direction
        type: string
      error:
        description: |-
          Empty if the transaction was successful,
          else error explaining why the transaction failed (optional)
        type: string
      fee:
        description: Transaction fee (native currency)
        type: string
      from:
        description: Address of the transaction sender
        type: string
      id:
        description: Unique identifier
        type: string
      inputs:
        description: Input addresses
        items:
          $ref: '#/definitions/blockatlas.TxOutput'
        type: array
      memo:
        description: Meta data object
        type: string
      metadata:
        type: object
      outputs:
        description: Output addresses
        items:
          $ref: '#/definitions/blockatlas.TxOutput'
        type: array
      sequence:
        description: Transaction nonce or sequence
        type: integer
      status:
        description: Status of the transaction
        type: string
      to:
        description: Address of the transaction recipient
        type: string
      type:
        description: Type of metadata
        type: string
    type: object
  blockatlas.TxOutput:
    properties:
      address:
        type: string
      value:
        type: string
    type: object
  blockatlas.TxPage:
    items:
      properties:
        block:
          description: Height of the block the transaction was included in
          type: integer
        coin:
          description: SLIP-44 coin index of the platform
          type: integer
        date:
          description: Unix timestamp of the block the transaction was included in
          type: integer
        direction:
          description: Transaction Direction
          type: string
        error:
          description: |-
            Empty if the transaction was successful,
            else error explaining why the transaction failed (optional)
          type: string
        fee:
          description: Transaction fee (native currency)
          type: string
        from:
          description: Address of the transaction sender
          type: string
        id:
          description: Unique identifier
          type: string
        inputs:
          description: Input addresses
          items:
            $ref: '#/definitions/blockatlas.TxOutput'
          type: array
        memo:
          description: Meta data object
          type: string
        metadata:
          type: object
        outputs:
          description: Output addresses
          items:
            $ref: '#/definitions/blockatlas.TxOutput'
          type: array
        sequence:
          description: Transaction nonce or sequence
          type: integer
        status:
          description: Status of the transaction
          type: string
        to:
          description: Address of the transaction recipient
          type: string
        type:
          description: Type of metadata
          type: string
      type: object
    type: array
  coin.ExternalCoin:
    properties:
      coin:
        type: integer
      decimals:
        type: integer
      name:
        type: string
      symbol:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /metrics:
    get:
      description: Get application metrics
      operationId: metrics
      summary: Get Metrics
      tags:
      - metrics
  /ns/lookup:
    get:
      description: Lookup ENS/ZNS to find registered addresses
      operationId: lookup
      parameters:
      - description: string name
        in: query
        name: name
        type: string
      - description: string coin
        in: query
        name: coin
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.Resolved'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ApiError'
      summary: Lookup .eth / .zil addresses
      tags:
      - ns
  /observer/v1/status:
    get:
      consumes:
      - application/json
      description: Get coin status
      operationId: coin_status
      parameters:
      - default: Bearer test
        description: Bearer authorization header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CoinStatus'
      summary: Get coin status
      tags:
      - observer
      - subscriptions
  /observer/v1/webhook/register:
    delete:
      consumes:
      - application/json
      description: Delete a webhook for addresses transactions
      operationId: delete_webhook
      parameters:
      - description: Accounts subscriptions
        in: body
        name: subscriptions
        required: true
        schema:
          $ref: '#/definitions/api.Webhook'
          type: object
      - default: Bearer test
        description: Bearer authorization header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ObserverResponse'
      summary: Delete a webhook
      tags:
      - observer
      - subscriptions
    post:
      consumes:
      - application/json
      description: Create a webhook for addresses transactions
      operationId: create_webhook
      parameters:
      - description: Accounts subscriptions
        in: body
        name: subscriptions
        required: true
        schema:
          $ref: '#/definitions/api.Webhook'
          type: object
      - default: Bearer test
        description: Bearer authorization header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ObserverResponse'
      summary: Create a webhook
      tags:
      - observer
      - subscriptions
  /v1/{coin}/{address}:
    get:
      consumes:
      - application/json
      description: Get transactions from the address
      operationId: tx_v1
      parameters:
      - default: tezos
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q
        description: the query address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ApiError'
      summary: Get Transactions
      tags:
      - platform
      - tx
  /v1/{coin}/xpub/{xpub}:
    get:
      consumes:
      - application/json
      description: Get transactions from xpub address
      operationId: xpub
      parameters:
      - default: bitcoin
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: zpub6ruK9k6YGm8BRHWvTiQcrEPnFkuRDJhR7mPYzV2LDvjpLa5CuGgrhCYVZjMGcLcFqv9b2WvsFtY2Gb3xq8NVq8qhk9veozrA2W9QaWtihrC
        description: the xpub address
        in: path
        name: xpub
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.TxPage'
      summary: Get xpub transactions
      tags:
      - platform
      - tx
  /v2/{coin}/collections/{address}:
    get:
      consumes:
      - application/json
      description: Get all collections from the address
      operationId: collections
      parameters:
      - default: ethereum
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: 0x5574Cd97432cEd0D7Caf58ac3c4fEDB2061C98fB
        description: the query address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.CollectionPage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ApiError'
      summary: Get Collections
      tags:
      - platform
      - collection
  /v2/{coin}/collections/{address}/collection/:
    get:
      consumes:
      - application/json
      description: Get a collection from the address
      operationId: collection
      parameters:
      - default: ethereum
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: 0x0875BCab22dE3d02402bc38aEe4104e1239374a7
        description: the query address
        in: path
        name: address
        required: true
        type: string
      - default: 0x06012c8cf97bead5deae237070f9587f8e7a266d
        description: the query collection
        in: path
        name: collection_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.CollectionPage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ApiError'
      summary: Get Collection
      tags:
      - platform
      - collection
  /v2/{coin}/staking/delegations/{address}:
    get:
      consumes:
      - application/json
      description: Get stake delegations from the address
      operationId: delegations
      parameters:
      - default: tron
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: TPJYCz8ppZNyvw7pTwmjajcx4Kk1MmEUhD
        description: the query address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.DocsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ApiError'
      summary: Get Stake Delegations
      tags:
      - platform
      - staking
  /v2/{coin}/staking/validators:
    get:
      consumes:
      - application/json
      description: Get validators from the address
      operationId: validators
      parameters:
      - default: cosmos
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.DocsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ApiError'
      summary: Get Validators
      tags:
      - platform
      - staking
  /v2/{coin}/tokens/{address}:
    get:
      consumes:
      - application/json
      description: Get tokens from the address
      operationId: tokens
      parameters:
      - default: ethereum
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: 0x5574Cd97432cEd0D7Caf58ac3c4fEDB2061C98fB
        description: the query address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.CollectionPage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ApiError'
      summary: Get Tokens
      tags:
      - platform
      - token
  /v2/{coin}/transactions/{address}:
    get:
      consumes:
      - application/json
      description: Get transactions from the address
      operationId: tx_v2
      parameters:
      - default: tezos
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q
        description: the query address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.TxPage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ApiError'
      summary: Get Transactions
      tags:
      - platform
      - tx
  /v2/staking/delegations:
    post:
      consumes:
      - application/json
      description: Get Stake Delegations for multiple coins
      operationId: batch_delegations
      parameters:
      - description: Validators addresses and coins
        in: body
        name: delegations
        required: true
        schema:
          $ref: '#/definitions/api.AddressesRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.DelegationsBatchPage'
      summary: Get Multiple Stake Delegations
      tags:
      - platform
      - staking
swagger: "2.0"
